# platform: osx-64
name: lookie
channels:
  - conda-forge
  - default
dependencies:
  - async_generator
  - attrs
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - click
  - colorama
  - cryptography
  - geckodriver
  - h11
  - idna
  - importlib-metadata
  - jaraco-classes
  - keyring
  - libcxx
  - libffi
  - libsqlite
  - libzlib
  - lz4
  - more-itertools
  - ncurses
  - openssl
  - outcome
  - packaging
  - pip
  - pycparser
  - pycryptodome
  - pyopenssl
  - pysocks
  - python
  - python-dotenv
  - python_abi
  - readline
  - requests
  - selenium
  - setuptools
  - sniffio
  - sortedcontainers
  - tk
  - tqdm
  - trio
  - trio-websocket
  - typing_extensions
  - tzdata
  - urllib3
  - webdriver-manager
  - wheel
  - wsproto
  - xz
  - zipp
